name: money_manager
description: "Money Manager App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.0 # wymagana baza dla wszystkich usług
  firebase_auth: ^4.15.0 # jeśli chcesz logowanie
  cloud_firestore: ^4.13.0 # jeśli chcesz bazę danych

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
